### PR TITLE
Simplify version information patch

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

cc @bollwyvl

### CODE REVIEW

**Comment by xhochy** [comment]
Upstream PR: https://github.com/jaraco/zipp/pull/30

**Comment by nehaljwani** [comment]
Should we add a test which performs a sanity check for the version post installation?

**Comment by bollwyvl** [comment]
Maybe something like:
```bash
pip freeze | grep "{{ name }}=={{ version }}"
```
...or a suitably pythonic version: pulling out grep on windows seems heavy, and might mask other issues... but the discouragement of `pip` as a module makes it hard.

I feel like such a check (and probably `pip check`) should probably become standard issue: these are not fun problems and _particularly_ break complex stuff far removed from the actual issue. Perhaps could be added to the linter? Seems heavy.

**Comment by nehaljwani** [comment]
FWIW, I am okay with this merge request, if @bollwyvl is okay with it.

**Pull request merged**
