### PR TITLE
Bump to Python >= 3.8

### PR DESCRIPTION
**Pull request by johnhany97**
With https://github.com/jaraco/zipp/commit/4269d2771a1cd7aaf5b365a0108dcef5a3c029d6, consumers still on python 3.7 may end up picking this up and failing at runtime.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by johnhany97** [comment]
@conda-forge-admin, please rerender

**Comment by johnhany97** [comment]
@nehaljwani would appreciate if you could review this PR at your earliest convenience

**Comment by dtreichler** [comment]
The build current on conda-forge breaks python 3.7 environments. Is it possible to retract or otherwise patch the existing package?

**Comment by nehaljwani** [comment]
One can open a PR at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock for patching the repodata.

**Comment by h-vetinari** [comment]
> The build current on conda-forge breaks python 3.7 environments.

While we shouldn't break things gratuitously (and I'm fine with fixing this case), Python 3.7 is end-of-life and has been completely dropped by conda-forge since almost a year.

It should be considered completely unsupported, and I strongly recommend to upgrade your pythons ASAP.

**Pull request merged**
